export const AlbumActionTypes = {
  CREATE_ALBUM: "CREATE_ALBUM",
  UPDATE_ALBUM: "UPDATE_ALBUM",
  DELETE_ALBUM: "DELETE_ALBUM",
  FETCH_ALBUMS: "FETCH_ALBUMS",
  PAGINATE_ALBUMS: "PAGINATE_ALBUMS",
};
