export const AlbumActionTypes = {
  CREATE_ALBUM: "CREATE_ALBUM",
  UPDATE_ALBUM: "UPDATE_ALBUM",
  DELETE_ALBUM: "DELETE_ALBUM",
  FETCH_ALBUMS: "FETCH_ALBUMS",
  PAGINATE_ALBUMS: "PAGINATE_ALBUMS",
  SET_EDITING_ALBUM_ID: "SET_EDITING_ALBUM_ID",
  TOGGLE_EDIT_MODE: "TOGGLE_EDIT_MODE",
};
